name: Build the font (courtesy of Bmono)
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Remove old build
        run: rm -rf dist

      - name: Install docker image
        run: |
          git clone --depth=1 https://github.com/be5invis/Iosevka.git $HOME/mkdkimg
          cd $HOME/mkdkimg/docker
          docker build -t=fontcc .
          cd ../..
          rm -rf mkdkimg/
          
      - name: Run build in docker
        run: | 
          docker run -it --rm -v $PWD:/work fontcc ttf::IosevkaCurlyLig ttf::IosevkaCurlyLigMono ttf::IosevkaCurlyLigTerm ttf::IosevkaCurlyLigPropo
