name: Build the font (courtesy of Bmono)
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Remove old build
        run: rm -rf dist

      - name: Install docker image
        run: |
          git clone --depth=1 https://github.com/be5invis/Iosevka.git $HOME/mkdkimg
          cd $HOME/mkdkimg/docker
          docker build -t=fontcc .
          cd ../..
          rm -rf mkdkimg/
          
      - name: Run build in docker
        run: | 
          cd $GITHUB_WORKSPACE
          docker run -i --rm -v $PWD:/work fontcc ttf::IosevkaCurlyLigs ttf::IosevkaCurlyLigsMono ttf::IosevkaCurlyLigsTerm ttf::IosevkaCurlyLigsPropo
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          
      - name: Add changes
        run: |
          git add dist/
          git commit -m "New build"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ env.TOKEN }}
        
